// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/server/app/repositories.go

// Package app is a generated GoMock package.
package app

import (
	context "context"
	sql "database/sql"
	types "go-yandex-practicum-metrics/internal/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFilterRepository is a mock of FilterRepository interface.
type MockFilterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFilterRepositoryMockRecorder
}

// MockFilterRepositoryMockRecorder is the mock recorder for MockFilterRepository.
type MockFilterRepositoryMockRecorder struct {
	mock *MockFilterRepository
}

// NewMockFilterRepository creates a new mock instance.
func NewMockFilterRepository(ctrl *gomock.Controller) *MockFilterRepository {
	mock := &MockFilterRepository{ctrl: ctrl}
	mock.recorder = &MockFilterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilterRepository) EXPECT() *MockFilterRepositoryMockRecorder {
	return m.recorder
}

// Filter mocks base method.
func (m *MockFilterRepository) Filter(ctx context.Context, filter types.MetricID) (*types.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, filter)
	ret0, _ := ret[0].(*types.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *MockFilterRepositoryMockRecorder) Filter(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockFilterRepository)(nil).Filter), ctx, filter)
}

// MockSaveRepository is a mock of SaveRepository interface.
type MockSaveRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSaveRepositoryMockRecorder
}

// MockSaveRepositoryMockRecorder is the mock recorder for MockSaveRepository.
type MockSaveRepositoryMockRecorder struct {
	mock *MockSaveRepository
}

// NewMockSaveRepository creates a new mock instance.
func NewMockSaveRepository(ctrl *gomock.Controller) *MockSaveRepository {
	mock := &MockSaveRepository{ctrl: ctrl}
	mock.recorder = &MockSaveRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSaveRepository) EXPECT() *MockSaveRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockSaveRepository) Save(ctx context.Context, metric *types.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSaveRepositoryMockRecorder) Save(ctx, metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSaveRepository)(nil).Save), ctx, metric)
}

// MockListRepository is a mock of ListRepository interface.
type MockListRepository struct {
	ctrl     *gomock.Controller
	recorder *MockListRepositoryMockRecorder
}

// MockListRepositoryMockRecorder is the mock recorder for MockListRepository.
type MockListRepositoryMockRecorder struct {
	mock *MockListRepository
}

// NewMockListRepository creates a new mock instance.
func NewMockListRepository(ctrl *gomock.Controller) *MockListRepository {
	mock := &MockListRepository{ctrl: ctrl}
	mock.recorder = &MockListRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListRepository) EXPECT() *MockListRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockListRepository) List(ctx context.Context) ([]*types.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*types.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockListRepositoryMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockListRepository)(nil).List), ctx)
}

// MockRepoConfig is a mock of RepoConfig interface.
type MockRepoConfig struct {
	ctrl     *gomock.Controller
	recorder *MockRepoConfigMockRecorder
}

// MockRepoConfigMockRecorder is the mock recorder for MockRepoConfig.
type MockRepoConfigMockRecorder struct {
	mock *MockRepoConfig
}

// NewMockRepoConfig creates a new mock instance.
func NewMockRepoConfig(ctrl *gomock.Controller) *MockRepoConfig {
	mock := &MockRepoConfig{ctrl: ctrl}
	mock.recorder = &MockRepoConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoConfig) EXPECT() *MockRepoConfigMockRecorder {
	return m.recorder
}

// GetDatabaseDSN mocks base method.
func (m *MockRepoConfig) GetDatabaseDSN() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseDSN")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDatabaseDSN indicates an expected call of GetDatabaseDSN.
func (mr *MockRepoConfigMockRecorder) GetDatabaseDSN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseDSN", reflect.TypeOf((*MockRepoConfig)(nil).GetDatabaseDSN))
}

// GetFileStoragePath mocks base method.
func (m *MockRepoConfig) GetFileStoragePath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileStoragePath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetFileStoragePath indicates an expected call of GetFileStoragePath.
func (mr *MockRepoConfigMockRecorder) GetFileStoragePath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileStoragePath", reflect.TypeOf((*MockRepoConfig)(nil).GetFileStoragePath))
}

// MockDBRepo is a mock of DBRepo interface.
type MockDBRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDBRepoMockRecorder
}

// MockDBRepoMockRecorder is the mock recorder for MockDBRepo.
type MockDBRepoMockRecorder struct {
	mock *MockDBRepo
}

// NewMockDBRepo creates a new mock instance.
func NewMockDBRepo(ctrl *gomock.Controller) *MockDBRepo {
	mock := &MockDBRepo{ctrl: ctrl}
	mock.recorder = &MockDBRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBRepo) EXPECT() *MockDBRepoMockRecorder {
	return m.recorder
}

// ExecContext mocks base method.
func (m *MockDBRepo) ExecContext(ctx context.Context, query string, args ...interface{}) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecContext", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecContext indicates an expected call of ExecContext.
func (mr *MockDBRepoMockRecorder) ExecContext(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecContext", reflect.TypeOf((*MockDBRepo)(nil).ExecContext), varargs...)
}

// QueryContext mocks base method.
func (m *MockDBRepo) QueryContext(ctx context.Context, query string, args ...interface{}) (*sql.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryContext", varargs...)
	ret0, _ := ret[0].(*sql.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryContext indicates an expected call of QueryContext.
func (mr *MockDBRepoMockRecorder) QueryContext(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryContext", reflect.TypeOf((*MockDBRepo)(nil).QueryContext), varargs...)
}

// QueryRowContext mocks base method.
func (m *MockDBRepo) QueryRowContext(ctx context.Context, query string, args ...interface{}) *sql.Row {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRowContext", varargs...)
	ret0, _ := ret[0].(*sql.Row)
	return ret0
}

// QueryRowContext indicates an expected call of QueryRowContext.
func (mr *MockDBRepoMockRecorder) QueryRowContext(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRowContext", reflect.TypeOf((*MockDBRepo)(nil).QueryRowContext), varargs...)
}

// MockFileRepo is a mock of FileRepo interface.
type MockFileRepo struct {
	ctrl     *gomock.Controller
	recorder *MockFileRepoMockRecorder
}

// MockFileRepoMockRecorder is the mock recorder for MockFileRepo.
type MockFileRepoMockRecorder struct {
	mock *MockFileRepo
}

// NewMockFileRepo creates a new mock instance.
func NewMockFileRepo(ctrl *gomock.Controller) *MockFileRepo {
	mock := &MockFileRepo{ctrl: ctrl}
	mock.recorder = &MockFileRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileRepo) EXPECT() *MockFileRepoMockRecorder {
	return m.recorder
}

// Decode mocks base method.
func (m *MockFileRepo) Decode(v interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decode indicates an expected call of Decode.
func (mr *MockFileRepoMockRecorder) Decode(v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockFileRepo)(nil).Decode), v)
}

// Encode mocks base method.
func (m *MockFileRepo) Encode(v interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Encode indicates an expected call of Encode.
func (mr *MockFileRepoMockRecorder) Encode(v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockFileRepo)(nil).Encode), v)
}

// Read mocks base method.
func (m *MockFileRepo) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockFileRepoMockRecorder) Read(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockFileRepo)(nil).Read), p)
}

// Seek mocks base method.
func (m *MockFileRepo) Seek(offset int64, whence int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seek", offset, whence)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seek indicates an expected call of Seek.
func (mr *MockFileRepoMockRecorder) Seek(offset, whence interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seek", reflect.TypeOf((*MockFileRepo)(nil).Seek), offset, whence)
}
