// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/server/app/services.go

// Package app is a generated GoMock package.
package app

import (
	context "context"
	sql "database/sql"
	types "go-yandex-practicum-metrics/internal/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockServiceFilterRepository is a mock of ServiceFilterRepository interface.
type MockServiceFilterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockServiceFilterRepositoryMockRecorder
}

// MockServiceFilterRepositoryMockRecorder is the mock recorder for MockServiceFilterRepository.
type MockServiceFilterRepositoryMockRecorder struct {
	mock *MockServiceFilterRepository
}

// NewMockServiceFilterRepository creates a new mock instance.
func NewMockServiceFilterRepository(ctrl *gomock.Controller) *MockServiceFilterRepository {
	mock := &MockServiceFilterRepository{ctrl: ctrl}
	mock.recorder = &MockServiceFilterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceFilterRepository) EXPECT() *MockServiceFilterRepositoryMockRecorder {
	return m.recorder
}

// Filter mocks base method.
func (m *MockServiceFilterRepository) Filter(ctx context.Context, filter types.MetricID) (*types.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, filter)
	ret0, _ := ret[0].(*types.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *MockServiceFilterRepositoryMockRecorder) Filter(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockServiceFilterRepository)(nil).Filter), ctx, filter)
}

// MockServiceSaveRepository is a mock of ServiceSaveRepository interface.
type MockServiceSaveRepository struct {
	ctrl     *gomock.Controller
	recorder *MockServiceSaveRepositoryMockRecorder
}

// MockServiceSaveRepositoryMockRecorder is the mock recorder for MockServiceSaveRepository.
type MockServiceSaveRepositoryMockRecorder struct {
	mock *MockServiceSaveRepository
}

// NewMockServiceSaveRepository creates a new mock instance.
func NewMockServiceSaveRepository(ctrl *gomock.Controller) *MockServiceSaveRepository {
	mock := &MockServiceSaveRepository{ctrl: ctrl}
	mock.recorder = &MockServiceSaveRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceSaveRepository) EXPECT() *MockServiceSaveRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockServiceSaveRepository) Save(ctx context.Context, metric *types.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockServiceSaveRepositoryMockRecorder) Save(ctx, metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockServiceSaveRepository)(nil).Save), ctx, metric)
}

// MockServiceListRepository is a mock of ServiceListRepository interface.
type MockServiceListRepository struct {
	ctrl     *gomock.Controller
	recorder *MockServiceListRepositoryMockRecorder
}

// MockServiceListRepositoryMockRecorder is the mock recorder for MockServiceListRepository.
type MockServiceListRepositoryMockRecorder struct {
	mock *MockServiceListRepository
}

// NewMockServiceListRepository creates a new mock instance.
func NewMockServiceListRepository(ctrl *gomock.Controller) *MockServiceListRepository {
	mock := &MockServiceListRepository{ctrl: ctrl}
	mock.recorder = &MockServiceListRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceListRepository) EXPECT() *MockServiceListRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockServiceListRepository) List(ctx context.Context) ([]*types.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*types.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServiceListRepositoryMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockServiceListRepository)(nil).List), ctx)
}

// MockRepoProvider is a mock of RepoProvider interface.
type MockRepoProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRepoProviderMockRecorder
}

// MockRepoProviderMockRecorder is the mock recorder for MockRepoProvider.
type MockRepoProviderMockRecorder struct {
	mock *MockRepoProvider
}

// NewMockRepoProvider creates a new mock instance.
func NewMockRepoProvider(ctrl *gomock.Controller) *MockRepoProvider {
	mock := &MockRepoProvider{ctrl: ctrl}
	mock.recorder = &MockRepoProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoProvider) EXPECT() *MockRepoProviderMockRecorder {
	return m.recorder
}

// GetFilterRepository mocks base method.
func (m *MockRepoProvider) GetFilterRepository() ServiceFilterRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilterRepository")
	ret0, _ := ret[0].(ServiceFilterRepository)
	return ret0
}

// GetFilterRepository indicates an expected call of GetFilterRepository.
func (mr *MockRepoProviderMockRecorder) GetFilterRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilterRepository", reflect.TypeOf((*MockRepoProvider)(nil).GetFilterRepository))
}

// GetListRepository mocks base method.
func (m *MockRepoProvider) GetListRepository() ServiceListRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListRepository")
	ret0, _ := ret[0].(ServiceListRepository)
	return ret0
}

// GetListRepository indicates an expected call of GetListRepository.
func (mr *MockRepoProviderMockRecorder) GetListRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListRepository", reflect.TypeOf((*MockRepoProvider)(nil).GetListRepository))
}

// GetSaveRepository mocks base method.
func (m *MockRepoProvider) GetSaveRepository() ServiceSaveRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSaveRepository")
	ret0, _ := ret[0].(ServiceSaveRepository)
	return ret0
}

// GetSaveRepository indicates an expected call of GetSaveRepository.
func (mr *MockRepoProviderMockRecorder) GetSaveRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSaveRepository", reflect.TypeOf((*MockRepoProvider)(nil).GetSaveRepository))
}

// MockTransaction is a mock of Transaction interface.
type MockTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionMockRecorder
}

// MockTransactionMockRecorder is the mock recorder for MockTransaction.
type MockTransactionMockRecorder struct {
	mock *MockTransaction
}

// NewMockTransaction creates a new mock instance.
func NewMockTransaction(ctrl *gomock.Controller) *MockTransaction {
	mock := &MockTransaction{ctrl: ctrl}
	mock.recorder = &MockTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransaction) EXPECT() *MockTransactionMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockTransaction) Begin() (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin")
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockTransactionMockRecorder) Begin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockTransaction)(nil).Begin))
}
