// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-yandex-practicum-metrics/internal/usecases/metric_update_batch_body.go

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	domain "go-yandex-practicum-metrics/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetricUpdateBatchBodyService is a mock of MetricUpdateBatchBodyService interface.
type MockMetricUpdateBatchBodyService struct {
	ctrl     *gomock.Controller
	recorder *MockMetricUpdateBatchBodyServiceMockRecorder
}

// MockMetricUpdateBatchBodyServiceMockRecorder is the mock recorder for MockMetricUpdateBatchBodyService.
type MockMetricUpdateBatchBodyServiceMockRecorder struct {
	mock *MockMetricUpdateBatchBodyService
}

// NewMockMetricUpdateBatchBodyService creates a new mock instance.
func NewMockMetricUpdateBatchBodyService(ctrl *gomock.Controller) *MockMetricUpdateBatchBodyService {
	mock := &MockMetricUpdateBatchBodyService{ctrl: ctrl}
	mock.recorder = &MockMetricUpdateBatchBodyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricUpdateBatchBodyService) EXPECT() *MockMetricUpdateBatchBodyServiceMockRecorder {
	return m.recorder
}

// UpdateBatch mocks base method.
func (m *MockMetricUpdateBatchBodyService) UpdateBatch(ctx context.Context, metrics []*domain.Metrics) ([]*domain.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBatch", ctx, metrics)
	ret0, _ := ret[0].([]*domain.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBatch indicates an expected call of UpdateBatch.
func (mr *MockMetricUpdateBatchBodyServiceMockRecorder) UpdateBatch(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBatch", reflect.TypeOf((*MockMetricUpdateBatchBodyService)(nil).UpdateBatch), ctx, metrics)
}
