// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-yandex-practicum-metrics/internal/usecases/metric_update_path.go

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	domain "go-yandex-practicum-metrics/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetricUpdatePathService is a mock of MetricUpdatePathService interface.
type MockMetricUpdatePathService struct {
	ctrl     *gomock.Controller
	recorder *MockMetricUpdatePathServiceMockRecorder
}

// MockMetricUpdatePathServiceMockRecorder is the mock recorder for MockMetricUpdatePathService.
type MockMetricUpdatePathServiceMockRecorder struct {
	mock *MockMetricUpdatePathService
}

// NewMockMetricUpdatePathService creates a new mock instance.
func NewMockMetricUpdatePathService(ctrl *gomock.Controller) *MockMetricUpdatePathService {
	mock := &MockMetricUpdatePathService{ctrl: ctrl}
	mock.recorder = &MockMetricUpdatePathServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricUpdatePathService) EXPECT() *MockMetricUpdatePathServiceMockRecorder {
	return m.recorder
}

// UpdateBatch mocks base method.
func (m *MockMetricUpdatePathService) UpdateBatch(ctx context.Context, metrics []*domain.Metrics) ([]*domain.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBatch", ctx, metrics)
	ret0, _ := ret[0].([]*domain.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBatch indicates an expected call of UpdateBatch.
func (mr *MockMetricUpdatePathServiceMockRecorder) UpdateBatch(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBatch", reflect.TypeOf((*MockMetricUpdatePathService)(nil).UpdateBatch), ctx, metrics)
}
