// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-yandex-practicum-metrics/internal/usecases/metric_update_path.go

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	domain "go-yandex-practicum-metrics/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetricUpdatePathService is a mock of MetricUpdatePathService interface.
type MockMetricUpdatePathService struct {
	ctrl     *gomock.Controller
	recorder *MockMetricUpdatePathServiceMockRecorder
}

// MockMetricUpdatePathServiceMockRecorder is the mock recorder for MockMetricUpdatePathService.
type MockMetricUpdatePathServiceMockRecorder struct {
	mock *MockMetricUpdatePathService
}

// NewMockMetricUpdatePathService creates a new mock instance.
func NewMockMetricUpdatePathService(ctrl *gomock.Controller) *MockMetricUpdatePathService {
	mock := &MockMetricUpdatePathService{ctrl: ctrl}
	mock.recorder = &MockMetricUpdatePathServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricUpdatePathService) EXPECT() *MockMetricUpdatePathServiceMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockMetricUpdatePathService) Update(ctx context.Context, metrics []*domain.Metrics) ([]*domain.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, metrics)
	ret0, _ := ret[0].([]*domain.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMetricUpdatePathServiceMockRecorder) Update(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMetricUpdatePathService)(nil).Update), ctx, metrics)
}

// MockMetricUpdateRequester is a mock of MetricUpdateRequester interface.
type MockMetricUpdateRequester struct {
	ctrl     *gomock.Controller
	recorder *MockMetricUpdateRequesterMockRecorder
}

// MockMetricUpdateRequesterMockRecorder is the mock recorder for MockMetricUpdateRequester.
type MockMetricUpdateRequesterMockRecorder struct {
	mock *MockMetricUpdateRequester
}

// NewMockMetricUpdateRequester creates a new mock instance.
func NewMockMetricUpdateRequester(ctrl *gomock.Controller) *MockMetricUpdateRequester {
	mock := &MockMetricUpdateRequester{ctrl: ctrl}
	mock.recorder = &MockMetricUpdateRequesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricUpdateRequester) EXPECT() *MockMetricUpdateRequesterMockRecorder {
	return m.recorder
}

// ToDomain mocks base method.
func (m *MockMetricUpdateRequester) ToDomain() []*domain.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToDomain")
	ret0, _ := ret[0].([]*domain.Metrics)
	return ret0
}

// ToDomain indicates an expected call of ToDomain.
func (mr *MockMetricUpdateRequesterMockRecorder) ToDomain() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToDomain", reflect.TypeOf((*MockMetricUpdateRequester)(nil).ToDomain))
}

// Validate mocks base method.
func (m *MockMetricUpdateRequester) Validate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockMetricUpdateRequesterMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockMetricUpdateRequester)(nil).Validate))
}

// MockMetricUpdateResponser is a mock of MetricUpdateResponser interface.
type MockMetricUpdateResponser struct {
	ctrl     *gomock.Controller
	recorder *MockMetricUpdateResponserMockRecorder
}

// MockMetricUpdateResponserMockRecorder is the mock recorder for MockMetricUpdateResponser.
type MockMetricUpdateResponserMockRecorder struct {
	mock *MockMetricUpdateResponser
}

// NewMockMetricUpdateResponser creates a new mock instance.
func NewMockMetricUpdateResponser(ctrl *gomock.Controller) *MockMetricUpdateResponser {
	mock := &MockMetricUpdateResponser{ctrl: ctrl}
	mock.recorder = &MockMetricUpdateResponserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricUpdateResponser) EXPECT() *MockMetricUpdateResponserMockRecorder {
	return m.recorder
}

// ToResponse mocks base method.
func (m *MockMetricUpdateResponser) ToResponse() *[]byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToResponse")
	ret0, _ := ret[0].(*[]byte)
	return ret0
}

// ToResponse indicates an expected call of ToResponse.
func (mr *MockMetricUpdateResponserMockRecorder) ToResponse() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToResponse", reflect.TypeOf((*MockMetricUpdateResponser)(nil).ToResponse))
}
