// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-yandex-practicum-metrics/internal/repositories/metric_file_find.go

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFileQuerierEngine is a mock of FileQuerierEngine interface.
type MockFileQuerierEngine struct {
	ctrl     *gomock.Controller
	recorder *MockFileQuerierEngineMockRecorder
}

// MockFileQuerierEngineMockRecorder is the mock recorder for MockFileQuerierEngine.
type MockFileQuerierEngineMockRecorder struct {
	mock *MockFileQuerierEngine
}

// NewMockFileQuerierEngine creates a new mock instance.
func NewMockFileQuerierEngine(ctrl *gomock.Controller) *MockFileQuerierEngine {
	mock := &MockFileQuerierEngine{ctrl: ctrl}
	mock.recorder = &MockFileQuerierEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileQuerierEngine) EXPECT() *MockFileQuerierEngineMockRecorder {
	return m.recorder
}

// Query mocks base method.
func (m *MockFileQuerierEngine) Query(ctx context.Context, query string, args ...any) ([]any, bool) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockFileQuerierEngineMockRecorder) Query(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockFileQuerierEngine)(nil).Query), varargs...)
}
