// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-yandex-practicum-metrics/internal/repositories/metric_db_save.go

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDBExecutorEngine is a mock of DBExecutorEngine interface.
type MockDBExecutorEngine struct {
	ctrl     *gomock.Controller
	recorder *MockDBExecutorEngineMockRecorder
}

// MockDBExecutorEngineMockRecorder is the mock recorder for MockDBExecutorEngine.
type MockDBExecutorEngineMockRecorder struct {
	mock *MockDBExecutorEngine
}

// NewMockDBExecutorEngine creates a new mock instance.
func NewMockDBExecutorEngine(ctrl *gomock.Controller) *MockDBExecutorEngine {
	mock := &MockDBExecutorEngine{ctrl: ctrl}
	mock.recorder = &MockDBExecutorEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBExecutorEngine) EXPECT() *MockDBExecutorEngineMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDBExecutorEngine) Execute(ctx context.Context, query string, args ...any) bool {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Execute", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDBExecutorEngineMockRecorder) Execute(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDBExecutorEngine)(nil).Execute), varargs...)
}
