// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-yandex-practicum-metrics/internal/repositories/metric_db_find.go

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDBScannerEngine is a mock of DBScannerEngine interface.
type MockDBScannerEngine struct {
	ctrl     *gomock.Controller
	recorder *MockDBScannerEngineMockRecorder
}

// MockDBScannerEngineMockRecorder is the mock recorder for MockDBScannerEngine.
type MockDBScannerEngineMockRecorder struct {
	mock *MockDBScannerEngine
}

// NewMockDBScannerEngine creates a new mock instance.
func NewMockDBScannerEngine(ctrl *gomock.Controller) *MockDBScannerEngine {
	mock := &MockDBScannerEngine{ctrl: ctrl}
	mock.recorder = &MockDBScannerEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBScannerEngine) EXPECT() *MockDBScannerEngineMockRecorder {
	return m.recorder
}

// Scan mocks base method.
func (m *MockDBScannerEngine) Scan(ctx context.Context, query string, args ...any) (map[any]any, bool) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(map[any]any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Scan indicates an expected call of Scan.
func (mr *MockDBScannerEngineMockRecorder) Scan(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockDBScannerEngine)(nil).Scan), varargs...)
}

// MockDBQuerierEngine is a mock of DBQuerierEngine interface.
type MockDBQuerierEngine struct {
	ctrl     *gomock.Controller
	recorder *MockDBQuerierEngineMockRecorder
}

// MockDBQuerierEngineMockRecorder is the mock recorder for MockDBQuerierEngine.
type MockDBQuerierEngineMockRecorder struct {
	mock *MockDBQuerierEngine
}

// NewMockDBQuerierEngine creates a new mock instance.
func NewMockDBQuerierEngine(ctrl *gomock.Controller) *MockDBQuerierEngine {
	mock := &MockDBQuerierEngine{ctrl: ctrl}
	mock.recorder = &MockDBQuerierEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBQuerierEngine) EXPECT() *MockDBQuerierEngineMockRecorder {
	return m.recorder
}

// Query mocks base method.
func (m *MockDBQuerierEngine) Query(ctx context.Context, query string, args ...any) (DBScannerEngine, bool) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(DBScannerEngine)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockDBQuerierEngineMockRecorder) Query(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockDBQuerierEngine)(nil).Query), varargs...)
}
