// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-yandex-practicum-metrics/internal/repositories/metric_memory_save.go

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMemoryExecutorEngine is a mock of MemoryExecutorEngine interface.
type MockMemoryExecutorEngine struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryExecutorEngineMockRecorder
}

// MockMemoryExecutorEngineMockRecorder is the mock recorder for MockMemoryExecutorEngine.
type MockMemoryExecutorEngineMockRecorder struct {
	mock *MockMemoryExecutorEngine
}

// NewMockMemoryExecutorEngine creates a new mock instance.
func NewMockMemoryExecutorEngine(ctrl *gomock.Controller) *MockMemoryExecutorEngine {
	mock := &MockMemoryExecutorEngine{ctrl: ctrl}
	mock.recorder = &MockMemoryExecutorEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemoryExecutorEngine) EXPECT() *MockMemoryExecutorEngineMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockMemoryExecutorEngine) Execute(ctx context.Context, query string, args ...any) bool {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Execute", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockMemoryExecutorEngineMockRecorder) Execute(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockMemoryExecutorEngine)(nil).Execute), varargs...)
}
