// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-yandex-practicum-metrics/internal/repositories/metric_file_save.go

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFileExecutorEngine is a mock of FileExecutorEngine interface.
type MockFileExecutorEngine struct {
	ctrl     *gomock.Controller
	recorder *MockFileExecutorEngineMockRecorder
}

// MockFileExecutorEngineMockRecorder is the mock recorder for MockFileExecutorEngine.
type MockFileExecutorEngineMockRecorder struct {
	mock *MockFileExecutorEngine
}

// NewMockFileExecutorEngine creates a new mock instance.
func NewMockFileExecutorEngine(ctrl *gomock.Controller) *MockFileExecutorEngine {
	mock := &MockFileExecutorEngine{ctrl: ctrl}
	mock.recorder = &MockFileExecutorEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileExecutorEngine) EXPECT() *MockFileExecutorEngineMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockFileExecutorEngine) Execute(ctx context.Context, query string, args ...any) bool {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Execute", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockFileExecutorEngineMockRecorder) Execute(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockFileExecutorEngine)(nil).Execute), varargs...)
}
