// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-yandex-practicum-metrics/internal/services/metric_update.go

// Package services is a generated GoMock package.
package services

import (
	context "context"
	domain "go-yandex-practicum-metrics/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetricUpdateSaveBatchRepository is a mock of MetricUpdateSaveBatchRepository interface.
type MockMetricUpdateSaveBatchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricUpdateSaveBatchRepositoryMockRecorder
}

// MockMetricUpdateSaveBatchRepositoryMockRecorder is the mock recorder for MockMetricUpdateSaveBatchRepository.
type MockMetricUpdateSaveBatchRepositoryMockRecorder struct {
	mock *MockMetricUpdateSaveBatchRepository
}

// NewMockMetricUpdateSaveBatchRepository creates a new mock instance.
func NewMockMetricUpdateSaveBatchRepository(ctrl *gomock.Controller) *MockMetricUpdateSaveBatchRepository {
	mock := &MockMetricUpdateSaveBatchRepository{ctrl: ctrl}
	mock.recorder = &MockMetricUpdateSaveBatchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricUpdateSaveBatchRepository) EXPECT() *MockMetricUpdateSaveBatchRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockMetricUpdateSaveBatchRepository) Save(ctx context.Context, metrics []*domain.Metrics) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, metrics)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockMetricUpdateSaveBatchRepositoryMockRecorder) Save(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockMetricUpdateSaveBatchRepository)(nil).Save), ctx, metrics)
}

// MockMetricUpdateFindBatchRepository is a mock of MetricUpdateFindBatchRepository interface.
type MockMetricUpdateFindBatchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricUpdateFindBatchRepositoryMockRecorder
}

// MockMetricUpdateFindBatchRepositoryMockRecorder is the mock recorder for MockMetricUpdateFindBatchRepository.
type MockMetricUpdateFindBatchRepositoryMockRecorder struct {
	mock *MockMetricUpdateFindBatchRepository
}

// NewMockMetricUpdateFindBatchRepository creates a new mock instance.
func NewMockMetricUpdateFindBatchRepository(ctrl *gomock.Controller) *MockMetricUpdateFindBatchRepository {
	mock := &MockMetricUpdateFindBatchRepository{ctrl: ctrl}
	mock.recorder = &MockMetricUpdateFindBatchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricUpdateFindBatchRepository) EXPECT() *MockMetricUpdateFindBatchRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockMetricUpdateFindBatchRepository) Find(ctx context.Context, filters []domain.MetricID) (map[domain.MetricID]*domain.Metrics, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, filters)
	ret0, _ := ret[0].(map[domain.MetricID]*domain.Metrics)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockMetricUpdateFindBatchRepositoryMockRecorder) Find(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockMetricUpdateFindBatchRepository)(nil).Find), ctx, filters)
}

// MockTx is a mock of Tx interface.
type MockTx struct {
	ctrl     *gomock.Controller
	recorder *MockTxMockRecorder
}

// MockTxMockRecorder is the mock recorder for MockTx.
type MockTxMockRecorder struct {
	mock *MockTx
}

// NewMockTx creates a new mock instance.
func NewMockTx(ctrl *gomock.Controller) *MockTx {
	mock := &MockTx{ctrl: ctrl}
	mock.recorder = &MockTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTx) EXPECT() *MockTxMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockTx) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockTxMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockTx)(nil).Commit))
}

// Rollback mocks base method.
func (m *MockTx) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockTxMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockTx)(nil).Rollback))
}

// MockWithTx is a mock of WithTx interface.
type MockWithTx struct {
	ctrl     *gomock.Controller
	recorder *MockWithTxMockRecorder
}

// MockWithTxMockRecorder is the mock recorder for MockWithTx.
type MockWithTxMockRecorder struct {
	mock *MockWithTx
}

// NewMockWithTx creates a new mock instance.
func NewMockWithTx(ctrl *gomock.Controller) *MockWithTx {
	mock := &MockWithTx{ctrl: ctrl}
	mock.recorder = &MockWithTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithTx) EXPECT() *MockWithTxMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockWithTx) Begin(ctx context.Context) (Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockWithTxMockRecorder) Begin(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockWithTx)(nil).Begin), ctx)
}

// Do mocks base method.
func (m *MockWithTx) Do(ctx context.Context, fn func(Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockWithTxMockRecorder) Do(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockWithTx)(nil).Do), ctx, fn)
}
