// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-yandex-practicum-metrics/internal/services/metric_get_by_id.go

// Package services is a generated GoMock package.
package services

import (
	context "context"
	domain "go-yandex-practicum-metrics/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetricGetFindBatchRepository is a mock of MetricGetFindBatchRepository interface.
type MockMetricGetFindBatchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricGetFindBatchRepositoryMockRecorder
}

// MockMetricGetFindBatchRepositoryMockRecorder is the mock recorder for MockMetricGetFindBatchRepository.
type MockMetricGetFindBatchRepositoryMockRecorder struct {
	mock *MockMetricGetFindBatchRepository
}

// NewMockMetricGetFindBatchRepository creates a new mock instance.
func NewMockMetricGetFindBatchRepository(ctrl *gomock.Controller) *MockMetricGetFindBatchRepository {
	mock := &MockMetricGetFindBatchRepository{ctrl: ctrl}
	mock.recorder = &MockMetricGetFindBatchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricGetFindBatchRepository) EXPECT() *MockMetricGetFindBatchRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockMetricGetFindBatchRepository) Find(ctx context.Context, filters []domain.MetricID) (map[domain.MetricID]*domain.Metrics, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, filters)
	ret0, _ := ret[0].(map[domain.MetricID]*domain.Metrics)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockMetricGetFindBatchRepositoryMockRecorder) Find(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockMetricGetFindBatchRepository)(nil).Find), ctx, filters)
}
