// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/metric_updates.go

// Package services is a generated GoMock package.
package services

import (
	context "context"
	types "go-yandex-practicum-metrics/internal/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetricUpdatesSaveRepository is a mock of MetricUpdatesSaveRepository interface.
type MockMetricUpdatesSaveRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricUpdatesSaveRepositoryMockRecorder
}

// MockMetricUpdatesSaveRepositoryMockRecorder is the mock recorder for MockMetricUpdatesSaveRepository.
type MockMetricUpdatesSaveRepositoryMockRecorder struct {
	mock *MockMetricUpdatesSaveRepository
}

// NewMockMetricUpdatesSaveRepository creates a new mock instance.
func NewMockMetricUpdatesSaveRepository(ctrl *gomock.Controller) *MockMetricUpdatesSaveRepository {
	mock := &MockMetricUpdatesSaveRepository{ctrl: ctrl}
	mock.recorder = &MockMetricUpdatesSaveRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricUpdatesSaveRepository) EXPECT() *MockMetricUpdatesSaveRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockMetricUpdatesSaveRepository) Save(ctx context.Context, metric *types.Metrics, tx Transaction) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, metric, tx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockMetricUpdatesSaveRepositoryMockRecorder) Save(ctx, metric, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockMetricUpdatesSaveRepository)(nil).Save), ctx, metric, tx)
}

// MockMetricUpdatesFilterRepository is a mock of MetricUpdatesFilterRepository interface.
type MockMetricUpdatesFilterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricUpdatesFilterRepositoryMockRecorder
}

// MockMetricUpdatesFilterRepositoryMockRecorder is the mock recorder for MockMetricUpdatesFilterRepository.
type MockMetricUpdatesFilterRepositoryMockRecorder struct {
	mock *MockMetricUpdatesFilterRepository
}

// NewMockMetricUpdatesFilterRepository creates a new mock instance.
func NewMockMetricUpdatesFilterRepository(ctrl *gomock.Controller) *MockMetricUpdatesFilterRepository {
	mock := &MockMetricUpdatesFilterRepository{ctrl: ctrl}
	mock.recorder = &MockMetricUpdatesFilterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricUpdatesFilterRepository) EXPECT() *MockMetricUpdatesFilterRepositoryMockRecorder {
	return m.recorder
}

// Filter mocks base method.
func (m *MockMetricUpdatesFilterRepository) Filter(ctx context.Context, filter types.MetricID, tx Transaction) (*types.Metrics, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, filter, tx)
	ret0, _ := ret[0].(*types.Metrics)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *MockMetricUpdatesFilterRepositoryMockRecorder) Filter(ctx, filter, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockMetricUpdatesFilterRepository)(nil).Filter), ctx, filter, tx)
}

// MockTransaction is a mock of Transaction interface.
type MockTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionMockRecorder
}

// MockTransactionMockRecorder is the mock recorder for MockTransaction.
type MockTransactionMockRecorder struct {
	mock *MockTransaction
}

// NewMockTransaction creates a new mock instance.
func NewMockTransaction(ctrl *gomock.Controller) *MockTransaction {
	mock := &MockTransaction{ctrl: ctrl}
	mock.recorder = &MockTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransaction) EXPECT() *MockTransactionMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockTransaction) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockTransactionMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockTransaction)(nil).Commit))
}

// Rollback mocks base method.
func (m *MockTransaction) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockTransactionMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockTransaction)(nil).Rollback))
}
