// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-yandex-practicum-metrics/internal/services/metric_update.go

// Package services is a generated GoMock package.
package services

import (
	context "context"
	domain "go-yandex-practicum-metrics/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetricSaveBatchRepository is a mock of MetricSaveBatchRepository interface.
type MockMetricSaveBatchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricSaveBatchRepositoryMockRecorder
}

// MockMetricSaveBatchRepositoryMockRecorder is the mock recorder for MockMetricSaveBatchRepository.
type MockMetricSaveBatchRepositoryMockRecorder struct {
	mock *MockMetricSaveBatchRepository
}

// NewMockMetricSaveBatchRepository creates a new mock instance.
func NewMockMetricSaveBatchRepository(ctrl *gomock.Controller) *MockMetricSaveBatchRepository {
	mock := &MockMetricSaveBatchRepository{ctrl: ctrl}
	mock.recorder = &MockMetricSaveBatchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricSaveBatchRepository) EXPECT() *MockMetricSaveBatchRepositoryMockRecorder {
	return m.recorder
}

// SaveBatch mocks base method.
func (m *MockMetricSaveBatchRepository) SaveBatch(ctx context.Context, metrics []*domain.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatch", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBatch indicates an expected call of SaveBatch.
func (mr *MockMetricSaveBatchRepositoryMockRecorder) SaveBatch(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatch", reflect.TypeOf((*MockMetricSaveBatchRepository)(nil).SaveBatch), ctx, metrics)
}

// MockMetricFindBatchRepository is a mock of MetricFindBatchRepository interface.
type MockMetricFindBatchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricFindBatchRepositoryMockRecorder
}

// MockMetricFindBatchRepositoryMockRecorder is the mock recorder for MockMetricFindBatchRepository.
type MockMetricFindBatchRepositoryMockRecorder struct {
	mock *MockMetricFindBatchRepository
}

// NewMockMetricFindBatchRepository creates a new mock instance.
func NewMockMetricFindBatchRepository(ctrl *gomock.Controller) *MockMetricFindBatchRepository {
	mock := &MockMetricFindBatchRepository{ctrl: ctrl}
	mock.recorder = &MockMetricFindBatchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricFindBatchRepository) EXPECT() *MockMetricFindBatchRepositoryMockRecorder {
	return m.recorder
}

// FindBatch mocks base method.
func (m *MockMetricFindBatchRepository) FindBatch(ctx context.Context, filters []domain.MetricID) (map[domain.MetricID]*domain.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBatch", ctx, filters)
	ret0, _ := ret[0].(map[domain.MetricID]*domain.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBatch indicates an expected call of FindBatch.
func (mr *MockMetricFindBatchRepositoryMockRecorder) FindBatch(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBatch", reflect.TypeOf((*MockMetricFindBatchRepository)(nil).FindBatch), ctx, filters)
}

// MockTransaction is a mock of Transaction interface.
type MockTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionMockRecorder
}

// MockTransactionMockRecorder is the mock recorder for MockTransaction.
type MockTransactionMockRecorder struct {
	mock *MockTransaction
}

// NewMockTransaction creates a new mock instance.
func NewMockTransaction(ctrl *gomock.Controller) *MockTransaction {
	mock := &MockTransaction{ctrl: ctrl}
	mock.recorder = &MockTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransaction) EXPECT() *MockTransactionMockRecorder {
	return m.recorder
}

// WithTransaction mocks base method.
func (m *MockTransaction) WithTransaction(ctx context.Context, fn func(context.Context) (any, error)) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockTransactionMockRecorder) WithTransaction(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockTransaction)(nil).WithTransaction), ctx, fn)
}
