// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/metric_get_by_type_and_id.go

// Package services is a generated GoMock package.
package services

import (
	context "context"
	types "go-yandex-practicum-metrics/internal/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetricGetByTypeAndIDFilterRepository is a mock of MetricGetByTypeAndIDFilterRepository interface.
type MockMetricGetByTypeAndIDFilterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricGetByTypeAndIDFilterRepositoryMockRecorder
}

// MockMetricGetByTypeAndIDFilterRepositoryMockRecorder is the mock recorder for MockMetricGetByTypeAndIDFilterRepository.
type MockMetricGetByTypeAndIDFilterRepositoryMockRecorder struct {
	mock *MockMetricGetByTypeAndIDFilterRepository
}

// NewMockMetricGetByTypeAndIDFilterRepository creates a new mock instance.
func NewMockMetricGetByTypeAndIDFilterRepository(ctrl *gomock.Controller) *MockMetricGetByTypeAndIDFilterRepository {
	mock := &MockMetricGetByTypeAndIDFilterRepository{ctrl: ctrl}
	mock.recorder = &MockMetricGetByTypeAndIDFilterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricGetByTypeAndIDFilterRepository) EXPECT() *MockMetricGetByTypeAndIDFilterRepositoryMockRecorder {
	return m.recorder
}

// Filter mocks base method.
func (m *MockMetricGetByTypeAndIDFilterRepository) Filter(ctx context.Context, filter types.MetricID) (*types.Metrics, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, filter)
	ret0, _ := ret[0].(*types.Metrics)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *MockMetricGetByTypeAndIDFilterRepositoryMockRecorder) Filter(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockMetricGetByTypeAndIDFilterRepository)(nil).Filter), ctx, filter)
}
