// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-yandex-practicum-metrics/internal/services/metric_list.go

// Package services is a generated GoMock package.
package services

import (
	context "context"
	domain "go-yandex-practicum-metrics/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetricListRepository is a mock of MetricListRepository interface.
type MockMetricListRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricListRepositoryMockRecorder
}

// MockMetricListRepositoryMockRecorder is the mock recorder for MockMetricListRepository.
type MockMetricListRepositoryMockRecorder struct {
	mock *MockMetricListRepository
}

// NewMockMetricListRepository creates a new mock instance.
func NewMockMetricListRepository(ctrl *gomock.Controller) *MockMetricListRepository {
	mock := &MockMetricListRepository{ctrl: ctrl}
	mock.recorder = &MockMetricListRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricListRepository) EXPECT() *MockMetricListRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockMetricListRepository) List(ctx context.Context) (map[domain.MetricID]*domain.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].(map[domain.MetricID]*domain.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMetricListRepositoryMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMetricListRepository)(nil).List), ctx)
}
