// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-yandex-practicum-metrics/internal/services/metric_update.go

// Package services is a generated GoMock package.
package services

import (
	context "context"
	sql "database/sql"
	domain "go-yandex-practicum-metrics/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetricUpdateSaveBatchRepository is a mock of MetricUpdateSaveBatchRepository interface.
type MockMetricUpdateSaveBatchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricUpdateSaveBatchRepositoryMockRecorder
}

// MockMetricUpdateSaveBatchRepositoryMockRecorder is the mock recorder for MockMetricUpdateSaveBatchRepository.
type MockMetricUpdateSaveBatchRepositoryMockRecorder struct {
	mock *MockMetricUpdateSaveBatchRepository
}

// NewMockMetricUpdateSaveBatchRepository creates a new mock instance.
func NewMockMetricUpdateSaveBatchRepository(ctrl *gomock.Controller) *MockMetricUpdateSaveBatchRepository {
	mock := &MockMetricUpdateSaveBatchRepository{ctrl: ctrl}
	mock.recorder = &MockMetricUpdateSaveBatchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricUpdateSaveBatchRepository) EXPECT() *MockMetricUpdateSaveBatchRepositoryMockRecorder {
	return m.recorder
}

// SaveBatch mocks base method.
func (m *MockMetricUpdateSaveBatchRepository) SaveBatch(ctx context.Context, metrics []*domain.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatch", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBatch indicates an expected call of SaveBatch.
func (mr *MockMetricUpdateSaveBatchRepositoryMockRecorder) SaveBatch(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatch", reflect.TypeOf((*MockMetricUpdateSaveBatchRepository)(nil).SaveBatch), ctx, metrics)
}

// MockMetricUpdateFindBatchRepository is a mock of MetricUpdateFindBatchRepository interface.
type MockMetricUpdateFindBatchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricUpdateFindBatchRepositoryMockRecorder
}

// MockMetricUpdateFindBatchRepositoryMockRecorder is the mock recorder for MockMetricUpdateFindBatchRepository.
type MockMetricUpdateFindBatchRepositoryMockRecorder struct {
	mock *MockMetricUpdateFindBatchRepository
}

// NewMockMetricUpdateFindBatchRepository creates a new mock instance.
func NewMockMetricUpdateFindBatchRepository(ctrl *gomock.Controller) *MockMetricUpdateFindBatchRepository {
	mock := &MockMetricUpdateFindBatchRepository{ctrl: ctrl}
	mock.recorder = &MockMetricUpdateFindBatchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricUpdateFindBatchRepository) EXPECT() *MockMetricUpdateFindBatchRepositoryMockRecorder {
	return m.recorder
}

// FindBatch mocks base method.
func (m *MockMetricUpdateFindBatchRepository) FindBatch(ctx context.Context, filters []domain.MetricID) (map[domain.MetricID]*domain.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBatch", ctx, filters)
	ret0, _ := ret[0].(map[domain.MetricID]*domain.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBatch indicates an expected call of FindBatch.
func (mr *MockMetricUpdateFindBatchRepositoryMockRecorder) FindBatch(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBatch", reflect.TypeOf((*MockMetricUpdateFindBatchRepository)(nil).FindBatch), ctx, filters)
}

// MockTxBeginer is a mock of TxBeginer interface.
type MockTxBeginer struct {
	ctrl     *gomock.Controller
	recorder *MockTxBeginerMockRecorder
}

// MockTxBeginerMockRecorder is the mock recorder for MockTxBeginer.
type MockTxBeginerMockRecorder struct {
	mock *MockTxBeginer
}

// NewMockTxBeginer creates a new mock instance.
func NewMockTxBeginer(ctrl *gomock.Controller) *MockTxBeginer {
	mock := &MockTxBeginer{ctrl: ctrl}
	mock.recorder = &MockTxBeginerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxBeginer) EXPECT() *MockTxBeginerMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockTxBeginer) BeginTx(ctx context.Context, opts *sql.TxOptions) (Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, opts)
	ret0, _ := ret[0].(Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockTxBeginerMockRecorder) BeginTx(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockTxBeginer)(nil).BeginTx), ctx, opts)
}

// MockTx is a mock of Tx interface.
type MockTx struct {
	ctrl     *gomock.Controller
	recorder *MockTxMockRecorder
}

// MockTxMockRecorder is the mock recorder for MockTx.
type MockTxMockRecorder struct {
	mock *MockTx
}

// NewMockTx creates a new mock instance.
func NewMockTx(ctrl *gomock.Controller) *MockTx {
	mock := &MockTx{ctrl: ctrl}
	mock.recorder = &MockTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTx) EXPECT() *MockTxMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockTx) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockTxMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockTx)(nil).Commit))
}

// Rollback mocks base method.
func (m *MockTx) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockTxMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockTx)(nil).Rollback))
}
